version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "O365HealthChecker"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h3rh909otqsm"
s3_prefix = "O365HealthChecker"
