AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Office365 Health.
  An app to fetch O365 Health Status and push it to Coralogix

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
Resources:
  O365HealthChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: o365_healthstatus_lambda_app/
      Handler: app.lambda_handler
      Runtime: python3.9
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          PRIVATE_KEY: "PRIVATE_KEY"
          APPLICATION_NAME: "Office"
          SUBSYSTEM_NAME: "Health"
          CLIENT_ID: "CLIENT_ID"
          CLIENT_SECRET: "CLIENT_SECRET"
          TENANT: "TENANT"